<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../UrlGetter.php';

/**
 * Test class for UrlGetter.
 * Generated by PHPUnit on 2010-09-17 at 20:54:26.
 */
class UrlGetterTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var UrlGetter
	 */
	protected $obj;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->plosXmlUrl = 'http://www.plosone.org/article/fetchObjectAttachment.action?uri=info%3Adoi%2F10.1371%2Fjournal.pone.0001305&representation=XML';
		$this->plosHtmlUrl = 'http://www.plosone.org/article/info:doi/10.1371/journal.pone.0001305';
		$this->deadUrl = 'http://jasonpriem.com/123fakestreet';
		$this->getter = new UrlGetter();
	}


	public function testGetReturnsString() {
		$this->getter->setUrl($this->plosXmlUrl);
		$this->getter->setReturnSimpleXml(false);
		$str = $this->getter->get();
		$this->assertXmlStringEqualsXmlFile(
				  dirname(__FILE__) . '/journal.pone.0001305.xml',
				  $str
				  );
	}

	public function testGetReturnsSimpleXmlObjectFromXmlString() {
		$this->getter->setUrl($this->plosXmlUrl);
		$this->assertEquals(
				  'SimpleXMLElement',
				  get_class($this->getter->get())
							 );
	}
	public function testGetReturnsSimpleXmlObjectFromHtmlString() {
		$this->getter->setUrl($this->plosHtmlUrl);
		$this->assertEquals(
				  'SimpleXMLElement',
				  get_class($this->getter->get())
							 );
	}
	public function testGetThrowsExceptionForBadUrl() {
//		$this->setExpectedException('Exception');
		$this->getter->setUrl($this->deadUrl);
		$this->getter->get();

	}
}
?>
